# Generated by Django 3.2.8 on 2021-10-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createposts',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='createposts',
            name='edit_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
