# Generated by Django 3.2.8 on 2021-10-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_alter_createposts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createposts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
