# Generated by Django 3.2.8 on 2021-10-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_alter_createposts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='createposts',
            name='hide_show',
            field=models.BooleanField(default=False),
        ),
    ]
