# Generated by Django 3.2.8 on 2021-10-31 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0007_auto_20211031_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePost',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=255, null=True)),
                ('post_text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('hide_show', models.BooleanField(default=False)),
                ('post_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='commentsadd',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.createpost'),
        ),
        migrations.DeleteModel(
            name='CreatePosts',
        ),
    ]
